contact_links:
  - name: Questions or general discussion with the community
    url: https://github.com/executablebooks/meta/discussions
    about: Use our Community Forum for general conversations that aren't meant for actionable Issues.
