# Inspired by
# - https://www.backhub.co/blog/best-practices-for-using-github-issues
# - https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
# - https://wiredcraft.com/blog/how-we-write-our-github-issues/
name: Request an enhancement 💡
description: Suggest an idea for this project
labels: [enhancement]
body:
- type: textarea
  id: describe
  attributes:
    label: Describe the problem/need and solution
    description: |
      - Describe the problem or need you'd like to address.
      - Include enough context so that somebody can quickly understand the need.
      - Note what kind of users would benefit from this solution. 
    value: |
      **Context**
      In situations where you're trying to do XXX.

      **Problem / Idea**
      You also want to do YYY, but this isn't currently possible.

      **Solution**
      We could make YYY possible by adding ZZZ new features.

      **Benefit**
      This would benefit the people trying to do XXX because...

  validations:
    required: true


- type: textarea
  id: implementation
  attributes:
    label: Guide for implementation
    description: |
      Any guidance that will help others understand how this issue could be addressed.
      Where appropriate, include:
      
      - locations in a codebase where a change would need to be made
      - rough mock-ups and design-level suggestions
      - screenshots of inspiration to take

    placeholder: |
      - This change would be probably need to be over here...
      - The best way to do this would be...
      - Here are links to tools with similar features...

  validations:
    required: false


- type: textarea
  id: tasks
  attributes:
    label: Tasks and updates
    description: |
      Use this area to track ongoing work and to-do items.
      The more specific the better.

      _If you can't think of anything then just leave this blank and we can fill it in later! This can be filled in as we understand more about an issue._

    placeholder: |
      - [ ] Discuss and decide on what to do...
      - [ ] Implement partial feature A...

  validations:
    required: false
